### ISSUE TITLE
Review and workaround for CloudFormation stack error > API: ec2:RunInstances Not authorized for images: [ami-XXXXXX]

### ISSUE THREAD

**Issue by ghost** [aws-samples/controltower-cloudendure-simulated-environment#4]
When running the stack with static Windows AMI, it may happen from time to time that a new Windows AMI is released making older ones deprecated, so the stack will fail to find the image for use. 

Quick workaround is to begin launching a similar Windows AMI, copy its AMI name and update the CloudFormation template in the same region (in the maps section) referring to it. As of January 2020, I am using Ohio's ami-0923bdaf73c766162 (Windows Server 2016 with SQL Server 2017).

Regards

**Comment by ccharro** [comment]
Hello! Thank you for you valuable feedback. I'm updating the latest AMI today and soon I'll update with the definitive solution to search for latest Windows AMIs. Thank you very much!
