### ISSUE TITLE
Problems with user data script

### ISSUE THREAD

**Issue by edircabsan** [aws-samples/controltower-cloudendure-simulated-environment#5]
Try to update the initial lines of the user data script with these lines:

            #!/bin/bash
            # Set environment variable to avoid unwanted confirmation dialogs
            export DEBIAN_FRONTEND=noninteractive
            # Install the files and packages from the metadata
            # install apache if not already installed
            apt-get -y update
            apt-get -y install npm apache2

**Comment by ccharro** [comment]
Thank you for your feedback. Just addressed the issue. Thank you.
